name: Debug Pipeline
on:
  workflow_dispatch:
jobs:
  prepare:
    name: Get Docker image version
    runs-on: ubuntu-latest
    outputs:
      imageName: ${{ steps.my-output.outputs.imageName }}
      imageVersion: ${{ steps.my-output.outputs.imageVersion }}
    steps:
    - id: my-output
      name: setOutput
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(image)
          core.setOutput('imageName', context.repo.repo);
          core.setOutput('imageVersion', '1.0.0');
          
    - name: debug
      run: |
        echo ${{ steps.my-output.outputs.imageName }}
        echo ${{ steps.my-output.outputs.imageVersion }}
  dev:
    name: dev
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Information
      run: |
        echo ${{ needs.prepare.outputs.imageName }}
        echo ${{ needs.prepare.outputs.imageVersion }}
